[package]
name = "dynamic_weather"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
env_logger = "0.11"

[dev-dependencies]
actix-rt = "2.5"
tokio = { version = "1", features = ["full"] }
